<?php

namespace TheBlog\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticleByTitre( $zTitre )
    {
        $qb = $this->createQueryBuilder('u')
            ->addSelect('u')
            ->where('u.titre LIKE :titre ')
            ->setParameter('titre', '%'.$zTitre.'%');

        return $qb->getQuery()->getResult();
    }
}
