<?php

namespace TheBlog\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageInfoRepository extends EntityRepository
{
}
