# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    utilisateurs.user_provider.class: Utilisateurs\UtilisateurBundle\UserProvider

services:
    utilisateurs.user_provider:
        class: %utilisateurs.user_provider.class%
        arguments: ["@fos_user.user_manager", {facebook: facebook_id}]
